USE CSET_ABET_DB
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'users')
	DROP TABLE users;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Course_ReqDeg')
	DROP TABLE Course_ReqDeg;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Course_Textbook')
	DROP TABLE Course_Textbook
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Course_Requisites')
	DROP TABLE Course_Requisites;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Course_ElectDeg')
	DROP TABLE Course_ElectDeg;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Course_PreRequisites')
	DROP TABLE Course_PreRequisites;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ReqTyps')
	DROP TABLE ReqTyps;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Course_SLO')
	DROP TABLE Course_SLO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Course_Professor')
	DROP TABLE Course_Professor
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'Requisite' AND TYPE = 'u')
	DROP TABLE Requisite
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ReqComment')
	DROP TABLE ReqComment
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ReqType')
	DROP TABLE ReqType;
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'Course' AND TYPE = 'u')
	DROP TABLE Course
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'Textbook_Author' AND TYPE = 'u')
	DROP TABLE Textbook_Author
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Textbook')
	DROP TABLE Textbook
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Author')
	DROP TABLE Author
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Publisher')
	DROP TABLE Publisher
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Professor')
	DROP TABLE Professor
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CourseNumber')
	DROP TABLE CourseNumber
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Department')
	DROP TABLE Department
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SLO')
	DROP TABLE SLO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SLODescription')
	DROP TABLE SLODescription
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CourseDescription')
	DROP TABLE CourseDescription
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Degree')
	DROP TABLE Degree
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DegreeLevel')
	DROP TABLE DegreeLevel
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Requisite')
	DROP TABLE Requisite
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ReqComment')
	DROP TABLE ReqComment
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Building')
	DROP TABLE Building
GO
USE master
GO
IF DB_ID('CSET_ABET_DB') IS NOT NULL
	DROP DATABASE [CSET_ABET_DB]
ELSE 
	print 'Unable to drop CSET_ABET_DB'
GO

-- drop indexes
IF DB_ID('books_idx') IS NOT NULL
	DROP INDEX [books_idx] ON [TextBook];
GO

IF DB_ID('authors_idx') IS NOT NULL
	DROP INDEX [authors_idx] ON [Author];
GO

IF DB_ID('publishers_idx') IS NOT NULL
	DROP INDEX [publishers_idx] ON [Publisher];
GO